---
- name: "Deploy service -> [{{ name }}]"
  ansible.builtin.docker_container:
    name: "{{ name }}"
    image: "{{ name }}"
    recreate: true
    ports:
      - "4000:80"
    healthcheck:
      test: "curl --fail http://localhost:80 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

#- name: "Remove not tageg images"
#  shell: 'docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
